services:
  app-local:
    build:
      context: ./src/streamlit
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - STREAMLIT_ENV=production
      - DATA_PROVIDER=LOCAL
      - DATA_PATH=./data
    ports:
      - "8502:8501"
  
  app-local-debug:
    build:
      context: ./src/streamlit
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "8503:8501" 
      - "9001:9001"
    environment:
      - DATA_PROVIDER=LOCAL
      - DATA_PATH=./data
      - DEBUG=1
  
  app-api-local:
    build:
      context: ./src/streamlit
      dockerfile: Dockerfile
    ports:
      - "8504:8501"
    environment:
      - STREAMLIT_ENV=production
      - DATA_PROVIDER=REMOTE
      - DATA_HOST=http://api-local:8080
    depends_on:
      - api-local
  
  app-api-local-debug:
    build:
      context: ./src/streamlit
      dockerfile: Dockerfile
    ports:
      - "8505:8501"
      - "9001:9001"
    environment:
      - DATA_PROVIDER=REMOTE
      - DATA_HOST=http://api-local:8080
      - DEBUG=1
    depends_on:
      - api-local

  api-local:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 3s

  api-db:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=timeseries
      - DB_USER=postgres
      - DB_PASSWORD=postgrespw
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 3s
  
  db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./data:/tmp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=timeseries
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "timeseries"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 5s
