services:

  app-build:
    build:
      context: ./src/streamlit
      dockerfile: Dockerfile
  
  app-base:
    extends:
      service: app-build
    ports:
      - "8502:8501"

  app-debug-base:
    extends:
      service: app-build
    ports:
      - "8502:8501"
      - "9001:9001"

  app-local:
    extends:
      service: app-base
    volumes:
      - ./data:/app/data
    environment:
      - STREAMLIT_ENV=production
      - DATA_PROVIDER=LOCAL
      - DATA_PATH=./data
  
  app-local-debug:
    extends:
      service: app-debug-base
    volumes:
      - ./data:/app/data
    environment:
      - DATA_PROVIDER=LOCAL
      - DATA_PATH=./data
      - DEBUG=1
  
  app-api-base:
    extends:
      service: app-base
    environment:
      - STREAMLIT_ENV=production
      - DATA_PROVIDER=REMOTE
      - DATA_HOST=http://api-local:8080

  app-api-local:
    extends:
      service: app-api-base
    depends_on:
      - api-local
  
  app-api-db:
    extends:
      service: app-api-base
    depends_on:
      - api-db
  
  app-api-debug-base:
    extends:
      service: app-debug-base
    environment:
      - DATA_PROVIDER=REMOTE
      - DATA_HOST=http://api-local:8080
      - DEBUG=1
  
  app-api-local-debug:
    extends:
      service: app-api-debug-base
    depends_on:
      - api-local
  
  app-api-db-debug:
    extends:
      service: app-api-debug-base
    depends_on:
      - api-db

  api-base:
    build:
      context: ./src/api
      dockerfile: Dockerfile

  api-local:
    extends:
      service: api-base
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 3s

  api-db:
    extends:
      service: api-base
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=timeseries
      - DB_USER=postgres
      - DB_PASSWORD=postgrespw
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 3s
  
  db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./data:/tmp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=timeseries
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "timeseries"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 5s
