x-common-service: &common-service
  build:
    context: ./src/streamlit
    dockerfile: Dockerfile
    target: streamlit
  ports:
    - "8501:8501"
  volumes:
    - ./data:/app/data

services:
  ts-viewer:
    <<: *common-service
    environment:
      - STREAMLIT_ENV=production
  
  ts-viewer-debug:
    <<: *common-service
    ports:
      - "8501:8501" 
      - "9001:9001"
    environment:
      - DEBUG=1

  ts-api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
