services:
  app-local:
    build:
      context: ./src/streamlit
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - STREAMLIT_ENV=production
      - DATA_PROVIDER=LOCAL
      - DATA_PATH=./data
    ports:
      - "8502:8501"
  
  app-local-debug:
    build:
      context: ./src/streamlit
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "8503:8501" 
      - "9001:9001"
    environment:
      - DATA_PROVIDER=LOCAL
      - DATA_PATH=./data
      - DEBUG=1

  ts-api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
